Site/TopCaster/Models/Entities/TextTypeItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Models
{
    public class TextTypeItem:BaseEntity
    {
        [Display(Name = "عنوان")]
        [MaxLength(200, ErrorMessage = "تعداد کاراکتر {0} نباید بیشتر از {1} باشد.")]
        public string Title { get; set; }
       
        [Display(Name = "متن توضیحات")]
        [Column(TypeName = "ntext")]
        [UIHint("RichText")]
        [DataType(DataType.MultilineText)]
        [AllowHtml]
       
        public string Body { get; set; }
        [Display(Name = "تصویر")]
        [MaxLength(200, ErrorMessage = "تعداد کاراکتر {0} نباید بیشتر از {1} باشد.")]

        public string ImageUrl { get; set; }
        [Display(Name = "گروه ")]
        public Guid TextTypeId { get; set; }

        public TextType TextType { get; set; }


        [MaxLength(100, ErrorMessage = "تعداد کاراکتر {0} نباید بیشتر از {1} باشد.")]
        public string Name { get; set; }
        internal class configuration : EntityTypeConfiguration<TextTypeItem>
        {
            public configuration()
            {
                HasRequired(p => p.TextType).WithMany(t => t.TextTypeItems).HasForeignKey(p => p.TextTypeId);
            }
        }

         
    }
}

Site/TopCaster/Controllers/TextTypeItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models;
using System.IO;

namespace TopCaster.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class TextTypeItemsController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: TextTypeItems
        public ActionResult Index(Guid id)
        {
            var textItems = db.TextTypeItems.Include(t => t.TextType).Where(t => t.IsDeleted == false && t.TextTypeId == id).OrderByDescending(t => t.CreationDate);
            return View(textItems.ToList());
        }
        [AllowAnonymous]
        public ActionResult Create(Guid id)
        {
            ViewBag.fk = id;
            ViewBag.TextTypeId = new SelectList(db.TextTypes.Where(current => current.IsDeleted == false && current.IsActive == true).ToList(),"Id","Title");
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Create(TextTypeItem textTypeItem,Guid id)
        {
            if (ModelState.IsValid)
            {
                textTypeItem.IsDeleted = false;
                textTypeItem.CreationDate = DateTime.Now;

                textTypeItem.Id = Guid.NewGuid();
                textTypeItem.TextTypeId = id;
                db.TextTypeItems.Add(textTypeItem);
                db.SaveChanges();
                return RedirectToAction("Index", new { @id = textTypeItem.TextTypeId });
            }
            ViewBag.fk = id;
            ViewBag.TextTypeId = new SelectList(db.TextTypes.Where(current => current.IsDeleted == false && current.IsActive == true).ToList(), "Id", "Title");
            return View(textTypeItem);
        }


        // GET: TextItems/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TextTypeItem textItems = db.TextTypeItems.Find(id);
            if (textItems == null)
            {
                return HttpNotFound();
            }
            ViewBag.fk = textItems.TextTypeId;
            return View(textItems);
        }

        // POST: TextItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TextTypeItem textItems, HttpPostedFileBase fileupload)
        {
            if (ModelState.IsValid)
            {
                #region Upload and resize image if needed
                string newFilenameUrl = string.Empty;

                if (fileupload != null)
                {
                    string filename = Path.GetFileName(fileupload.FileName);
                    string newFilename = Guid.NewGuid().ToString().Replace("-", string.Empty)
                                         + Path.GetExtension(filename);
                    newFilenameUrl = "/Uploads/Text/" + newFilename;
                    string physicalFilename = Server.MapPath(newFilenameUrl);
                    fileupload.SaveAs(physicalFilename);
                    textItems.ImageUrl = newFilenameUrl;
                }

                #endregion
                textItems.LastModifiedDate = DateTime.Now;
                textItems.IsDeleted = false;
                db.Entry(textItems).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { @id = textItems.TextTypeId });
            }
            return View(textItems);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Site/TopCaster/Views/TextTypeItems/Create.cshtml
@model Models.TextTypeItem

@{
    ViewBag.Title = "افزودن " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>افزودن @Html.DisplayNameFor(model => model)</h2>

@using (Html.BeginForm("Create", "TextTypeItems",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        @Html.ValidationSummary(true)

        <div class="form-group">
        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Title)

                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Body)

                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.Kendo().Upload().Name("fileUpload").Multiple(false)
                @Html.ValidationMessageFor(model => model.ImageUrl)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TextTypeId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TextTypeId", String.Empty)
                @Html.ValidationMessageFor(model => model.TextTypeId)
            </div>
        </div>

        <div class="form-group">
			<div class="col-md-2">
            </div>
            <div class="col-md-10">
                    @Html.EditorFor(model => model.IsActive)

				@Html.LabelFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)

                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ایجاد" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
        </div>
</div>
}

Site/TopCaster/Views/TextTypeItems/Edit.cshtml
@model Models.TextTypeItem

@{
    ViewBag.Title = "ویرایش " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "TextTypeItems",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.TextTypeId)
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Body, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body)

                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>
     
        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.Kendo().Upload().Name("fileUpload").Multiple(false)
	 @Html.HiddenFor(model => model.ImageUrl)
                @Html.ValidationMessageFor(model => model.ImageUrl)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActive)

                @Html.LabelFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>
        @Html.HiddenFor(model => model.CreationDate)
        <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index",new { id = ViewBag.fk })
            </div>
        </div>
    </div>
}

Site/TopCaster/Views/TextTypeItems/Index.cshtml
@model IEnumerable<Models.TextTypeItem>

@{
ViewBag.Title = "فهرست " + Server.HtmlDecode(Html.DisplyModelPluralName(model => model).ToString());
    
}

<h2>@ViewBag.Title</h2>

        @(Html.Kendo().Grid(Model)
              .Name("Grid")
              .Columns(columns =>
                  {
        columns.Bound(model => model.Title);
        
      
				columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
							.Template(@<text>
									@Html.ActionLink("ویرایش", "Edit", new {id = @item.Id}, new {@class = "k-button"})
									</text>).Width(200);  
		})     
		.DataSource(dataSource => dataSource
									.Server()
							
									.Model(model => model.Id(item => item.Id))
					)              
	)